version: '3'

services:
  web:
    image: mowie/mowie
    volumes:
      - ./data/apps:/var/www/apps # apps
      - ./data/config:/var/www/config # config
      - ./data/content:/var/www/content # contents of your website
      - ./data/session:/var/session # Session storage. Useful when using multiple instances of this container with a loadbalancer
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mariadb:latest
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234 # Changeme!
      - MYSQL_DATABASE=mowie
